project:
  type: website

website:
  title: "Dev notes for Quarto"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd

format:
  html:
    theme:
      - brand
    css: styles.css



